# Generated by Django 4.1.3 on 2022-11-05 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_alter_enterprisecontacts_enterprise_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
                ("model", models.CharField(max_length=64)),
                ("market_launch_date", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="enterpriseemployees",
            name="name",
        ),
        migrations.RemoveField(
            model_name="enterpriseproducts",
            name="market_launch_date",
        ),
        migrations.RemoveField(
            model_name="enterpriseproducts",
            name="model",
        ),
        migrations.RemoveField(
            model_name="enterpriseproducts",
            name="name",
        ),
        migrations.AddField(
            model_name="enterpriseemployees",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enterprise_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enterprisecontacts",
            name="city",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="enterprisecontacts",
            name="country",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="enterprisecontacts",
            name="email",
            field=models.EmailField(max_length=32),
        ),
        migrations.AlterField(
            model_name="enterprisecontacts",
            name="enterprise",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="app.enterprise",
            ),
        ),
        migrations.AlterField(
            model_name="enterprisecontacts",
            name="house_number",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="enterprisecontacts",
            name="the_outside",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="enterpriseemployees",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="app.enterprise",
            ),
        ),
        migrations.CreateModel(
            name="SupplyChainProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_chain",
                        to="app.enterpriseproducts",
                    ),
                ),
                (
                    "supply_chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_supply_chain",
                        to="app.supplychain",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enterpriseproducts",
            name="products",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enterprise",
                to="app.products",
            ),
            preserve_default=False,
        ),
    ]
