# Generated by Django 4.1.3 on 2022-11-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_enterprisecontacts_enterprise_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
                ("model", models.CharField(max_length=64)),
                ("market_launch_date", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="enterpriseproducts",
            name="market_launch_date",
        ),
        migrations.RemoveField(
            model_name="enterpriseproducts",
            name="model",
        ),
        migrations.RemoveField(
            model_name="enterpriseproducts",
            name="name",
        ),
        migrations.AddField(
            model_name="enterpriseproducts",
            name="products",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enterprise",
                to="app.products",
            ),
            preserve_default=False,
        ),
    ]
