# Generated by Django 4.1.3 on 2022-11-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprisecontacts",
            name="enterprise",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="app.enterprise",
            ),
        ),
    ]
