# Generated by Django 4.1.3 on 2022-11-04 13:51

from django.conf import settings
from django.db import migrations, models


def create(apps, schema_editor):
    Enterprise = apps.get_model('app', 'Enterprise')
    EnterpriseType = apps.get_model('app', 'EnterpriseType')
    EnterpriseContacts = apps.get_model('app', 'EnterpriseContacts')
    list_enterprise = {
        'Завод1': 1,
        'Дистрибьютор1': 2,
        'Дилерский центр1': 3,
        'Крупная розничная сеть1': 4,
        'Индивидуальный предприниматель1': 5,

    }
    list_query = []
    for name, type in list_enterprise.items():
        type = EnterpriseType.objects.get(pk=type)
        list_query.append(Enterprise(name=name, type=type))
    Enterprise.objects.bulk_create(list_query)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0004_products_remove_enterpriseemployees_name_and_more"),
    ]

    operations = [
        migrations.RunPython(create),
    ]
