# Generated by Django 4.1.3 on 2022-11-04 13:51
import datetime

from django.conf import settings
from django.db import migrations, models


def create(apps, schema_editor):
    Products = apps.get_model('app', 'Products')
    Enterprise = apps.get_model('app', 'Enterprise')
    EnterpriseContacts = apps.get_model('app', 'EnterpriseContacts')

    enterprise_contacts = {
        1: ['asdf@as.as', 'Беларусь', "Минск", "Улица", "1"],
        2: ['asdf1@as.as', 'Беларусь', "Гродно", "Улица", "1"],
        3: ['asdf2@as.as', 'Беларусь', "Витебск", "Улица", "1"],
        4: ['asdf3@as.as', 'Россия', "Москва", "Улица", "1"],
        5: ['asdf@as.as', 'Россия', "Питер", "Улица", "1"],
    }
    list_query = []
    for enterprise, value in enterprise_contacts.items():
        enterprise = Enterprise.objects.get(pk=enterprise)
        list_query.append(
            EnterpriseContacts(
                enterprise=enterprise,
                email=value[0],
                country=value[1],
                city=value[2],
                the_outside=value[3],
                house_number=value[4]
            )
        )
    EnterpriseContacts.objects.bulk_create(list_query)

    list_products = [
        ['Asus', '01', f"{datetime.date.today()}"],
        ['Aser', '02', f"{datetime.date.today()}"],
        ['Lenovo', '03', f"{datetime.date.today()}"],
        ['Huawei', '04', f"{datetime.date.today()}"],
        ['Samsung', '05', f"{datetime.date.today()}"],
    ]
    list_query = []
    for value in list_products:
        list_query.append(
            Products(
                name=value[0],
                model=value[1],
                market_launch_date=value[2],
            )
        )
    Products.objects.bulk_create(list_query)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0005_create_entries"),
    ]

    operations = [
        migrations.RunPython(create),
    ]
