# Generated by Django 4.1.3 on 2022-11-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_enterprisecontacts_contacts_enterprise_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="market_launch_date",
            field=models.DateTimeField(),
        ),
    ]
